### PR TITLE
Parser

### PR DESCRIPTION
**Pull request by Maher9596**
I made a function to parse the Markdown text to HTML.

I have also tested the function to make sure it works, You can see below: The Markdown text is parsed to HTML.

image

image

### CODE REVIEW

**Review by Ma7eer — CHANGES_REQUESTED** [review]
It seems you are parsing the markdown yourself with code. I think we should not do that. We should use a library to parse markdown as we won't be able to cover all cases by writing our own code. 

Remember we are building this Checklist app not a markdown parser.

**Comment by Maher9596** [comment]
### Refer to issue #12 to complete this PR

**Comment by Maher9596** [comment]
I used an NPM library to parse the Markdown,

I also tested it and it's working fine, You can see in the picture below MD text translated to HTML.

**The changes are pushed into the parser branch**

image

image

**Comment by Ma7eer** [comment]
We have a merge conflict. This seems to be due to you changing the `package.json` file. Did you delete the original?

**Review by Ma7eer — CHANGES_REQUESTED** [review]
- Why are we replacing the `index.html` file. We should be creating a new file for the markdown. 

- `package.json` file has been changed. Please review and return it to what it was.

- The `upload.js` file already exists. Why does it seem to be recreated. Not only that, but it is not formatted as discussed on PR #16

**Comment by Ma7eer** [comment]
I will close this PR as per issue #20 we are no longer uploading markdown files.

**Pull request closed without merging**
